#!/usr/bin/env node
// Build script: produces dist/chrome/ and dist/firefox/ from the single source extension.
// Chrome: uses service_worker for background
// Firefox: uses scripts array for background (event page)
//
// Pass --watch to rebuild on every change to a source file.

const fs = require('fs');
const path = require('path');

const SRC = __dirname;
const DIST = path.join(SRC, 'dist');
// Single source of truth for the version: the repo-root VERSION file. The
// version in manifest.json is a placeholder — it is overwritten here so the
// extension version never has to be bumped separately from the binary.
const VERSION = fs.readFileSync(path.join(SRC, '..', 'VERSION'), 'utf8').trim();
const SHARED = ['background.js', 'content.js', 'popup.html', 'popup.js'];
// Directory trees copied verbatim into each dist target. The browser
// consumes `icons/` via manifest.icons + manifest.action.default_icon.
const SHARED_DIRS = ['icons'];
const WATCHED = [...SHARED, 'manifest.json'];

function copyDir(src, dst) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function build() {
  const manifest = JSON.parse(fs.readFileSync(path.join(SRC, 'manifest.json'), 'utf8'));

  for (const target of ['chrome', 'firefox']) {
    const out = path.join(DIST, target);
    fs.mkdirSync(out, { recursive: true });

    // Copy shared files
    for (const f of SHARED) {
      const src = path.join(SRC, f);
      if (fs.existsSync(src)) {
        fs.copyFileSync(src, path.join(out, f));
      }
    }
    for (const d of SHARED_DIRS) {
      copyDir(path.join(SRC, d), path.join(out, d));
    }

    // Build target-specific manifest
    const m = JSON.parse(JSON.stringify(manifest));
    m.version = VERSION; // stamp from the repo-root VERSION file (single source)

    if (target === 'firefox') {
      // Firefox MV3: uses scripts array, not service_worker
      m.background = { scripts: ['background.js'] };
      // Firefox has no chrome.debugger API — the cdp_* tools are Chrome-only
      // (Firefox uses WebDriver BiDi instead). Strip the permission so the
      // signed XPI doesn't trip an "unknown permission" lint warning.
      m.permissions = m.permissions.filter((p) => p !== 'debugger');
      // Add gecko settings
      // update_url enables auto-update for the self-distributed (unlisted)
      // signed XPI. Firefox polls this JSON daily; when version > installed,
      // it downloads the linked .xpi and replaces the extension. The URL
      // resolves to the firefox-updates.json asset on the latest GitHub
      // release — generated by `make firefox-updates-json` and uploaded
      // with every release. The URL is part of the SIGNED manifest, so
      // changing it later requires re-signing under a new version.
      m.browser_specific_settings = {
        gecko: {
          id: 'turboweb-mcp@ikari.pl',
          strict_min_version: '128.0',
          update_url: 'https://github.com/ikari-software/turboweb-mcp/releases/latest/download/firefox-updates.json',
        },
      };
      // Display name in Firefox — same as Chrome's, kept consistent
      // since the extension is browser-agnostic.
      m.name = 'TurboWeb MCP by ikari';
      m.action.default_title = 'TurboWeb MCP by ikari';
      // Adaptive toolbar icon: Firefox automatically serves the light-mode SVG
      // when the browser has a light theme (e.g. Zen in light mode), and the
      // dark-mode PNGs otherwise.  Chrome has no equivalent; the dark PNGs
      // remain the default there and are still visible on light toolbars.
      m.action.theme_icons = [
        { light: 'icons/app-icon-light.svg', dark: 'icons/app-icon-16.png',  size: 16  },
        { light: 'icons/app-icon-light.svg', dark: 'icons/app-icon-32.png',  size: 32  },
        { light: 'icons/app-icon-light.svg', dark: 'icons/app-icon-48.png',  size: 48  },
        { light: 'icons/app-icon-light.svg', dark: 'icons/app-icon-128.png', size: 128 },
      ];
      // Explicit CSP: under its default extension policy Firefox upgrades
      // ws://127.0.0.1 → wss:// for extension pages, which the local daemon
      // (plain ws://, no TLS) can't answer — the connection just fails.
      // Declaring our own extension_pages CSP replaces that default (no
      // implicit upgrade) and whitelists the loopback endpoints the
      // background script actually talks to: the daemon WS (:18321), the
      // native screenshot resizer (:18322), and the drag_drop_file loopback
      // file host (:18323). Chrome doesn't upgrade loopback, so this is
      // Firefox-only. Note this CSP governs extension *pages*, not content
      // scripts — drag_drop_file fetches the file from the content script's
      // isolated world, which this does not gate; the :18323 entry is for
      // defence-in-depth/consistency with the resizer convention.
      m.content_security_policy = {
        extension_pages:
          "script-src 'self'; object-src 'self'; " +
          "connect-src 'self' ws://127.0.0.1:18321 ws://localhost:18321 " +
          "http://127.0.0.1:18322 http://127.0.0.1:18323",
      };
    }

    fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify(m, null, 2) + '\n');
  }
}

function buildLogged() {
  const t0 = Date.now();
  try {
    build();
    const ms = Date.now() - t0;
    console.log(`[${new Date().toLocaleTimeString('en-GB', { hour12: false })}] built dist/{chrome,firefox} in ${ms}ms`);
  } catch (e) {
    console.error(`[build] failed: ${e.message}`);
  }
}

// Watch mode: rebuild on any change to a source file. Uses fs.watch (which is
// edge-triggered and noisy on macOS), so we debounce to a single rebuild per
// 150ms burst.
function watch() {
  buildLogged();
  console.log('[watch] watching extension/ for changes…');

  let timer = null;
  const triggerRebuild = (filename) => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      timer = null;
      console.log(`[watch] change: ${filename}`);
      buildLogged();
    }, 150);
  };

  fs.watch(SRC, { persistent: true }, (_event, filename) => {
    if (!filename) return;
    if (!WATCHED.includes(filename)) return;
    triggerRebuild(filename);
  });
}

if (process.argv.includes('--watch')) {
  watch();
} else {
  buildLogged();
}
